package com.ballc.gasuite;

// Generated Apr 14, 2011 11:38:01 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AccessToken generated by hbm2java
 */
public class AccessToken implements java.io.Serializable {

	private String loginName;
	private long accessTokenId;
	private String accessToken;
	private String secret;
	private Date modifiedDate;

	public AccessToken() {
	}

	public AccessToken(String loginName, long accessTokenId,
			String accessToken, String secret, Date modifiedDate) {
		this.loginName = loginName;
		this.accessTokenId = accessTokenId;
		this.accessToken = accessToken;
		this.secret = secret;
		this.modifiedDate = modifiedDate;
	}

	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public long getAccessTokenId() {
		return this.accessTokenId;
	}

	public void setAccessTokenId(long accessTokenId) {
		this.accessTokenId = accessTokenId;
	}

	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	public String getSecret() {
		return this.secret;
	}

	public void setSecret(String secret) {
		this.secret = secret;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
